index:
    path: /
    defaults: { _controller: StoreFrontendBundle:Home:index }

index_by_category:
    path: /{categoryId}/c_index
    defaults: { _controller: StoreFrontendBundle:Home:index }

index_by_tag:
    path: /{tagId}/t_index
    defaults: { _controller: StoreFrontendBundle:Home:index }

find_product_by_id:
    path: /{id}/product
    defaults: { _controller: StoreFrontendBundle:Home:product }
    requirements:
        id: \d+

add_to_cart:
    path: /{productId}/add_to_cart
    defaults: { _controller: StoreFrontendBundle:Cart:addCart }

add_to_cart_and_checkout:
    path: /{productId}/add_to_cart_and_pay
    defaults: { _controller: StoreFrontendBundle:Cart:addCartAndPay }

remove_from_cart:
    path: /{id}/remove_from_cart
    defaults: { _controller: StoreFrontendBundle:Cart:removeItem }

add_to_cart_success:
    path: /add_to_cart_success
    defaults: { _controller: StoreFrontendBundle:Cart:index }

checkout_dashboard:
    path: /check_out
    defaults: { _controller: StoreFrontendBundle:Cart:dashboard }

shipment_dashboard:
    path: /shipment_dashboard
    defaults: { _controller: StoreFrontendBundle:Home:shipment }

set_default_address:
    path: /{id}/set_as_default_address
    defaults: { _controller: StoreFrontendBundle:Cart:setDefaultAddress }

cart_to_payment:
    path: /{cartId}/payment
    defaults: { _controller: StoreFrontendBundle:Payment:index }

cart_to_shipment:
    path: /{cartId}/{shipmentId}/set_shipment
    defaults: { _controller: StoreFrontendBundle:Payment:selectShipment }

create_payment:
    path: /{cartId}/create_payment
    defaults: { _controller: StoreFrontendBundle:Payment:createPayment }

alipay_notify:
    path: /notify.php
    defaults: { _controller: StoreFrontendBundle:Payment:notify }

alipay_return:
    path: /return.php
    defaults: { _controller: StoreFrontendBundle:Payment:return }

tracking_confirm:
    path: /{id}/confirm_shipment
    defaults: { _controller: StoreFrontendBundle:Home:confirm }

tracking_confirm_ok:
    path: /{id}/confirmed_shipment
    defaults: { _controller: StoreFrontendBundle:Home:confirmed }