index:
    path: /
    defaults: { _controller: StoreFrontendBundle:Home:index }

find_product_by_id:
    path: /{id}/product
    defaults: { _controller: StoreFrontendBundle:Home:product }
    requirements:
        id: \d+

add_to_cart:
    path: /add_to_cart_success
    defaults: { _controller: StoreFrontendBundle:Cart:index }