parameters:
#    store_frontend.example.class: Store\Bundle\FrontendBundle\Example

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
