store:
    path: /
    defaults: { _controller: StoreBackendBundle:Home:home }

######
product_manage:
    path:     /product
    defaults: { _controller: StoreBackendBundle:Product:index }

product_trash_manage:
    path:     /product_trash
    defaults: { _controller: StoreBackendBundle:Product:trash }

product_edit:
    path: /{id}/product
    defaults: { _controller: StoreBackendBundle:Product:edit }

product_gallery:
    path: /{id}/gallery
    defaults: { _controller: StoreBackendBundle:Product:gallery }

product_gallery_action:
    path: /{id}/gallery/{action}
    defaults: { _controller: StoreBackendBundle:Product:editGallery }

product_remove:
    path: /{id}/product/remove
    defaults: { _controller: StoreBackendBundle:Product:remove }

product_resume:
    path: /{id}/product/resume
    defaults: { _controller: StoreBackendBundle:Product:resume }

product_category:
    path: /product/category
    defaults: { _controller: StoreBackendBundle:Category:index }

product_category_edit:
    path: /{id}/category/edit
    defaults: { _controller: StoreBackendBundle:Category:edit }

product_to_category:
    path: /{productId}/addTo/{categoryId}/{dropCategory}
    defaults: { _controller: StoreBackendBundle:Category:addProductToCategory }

edit_product_property:
    path: /{id}/add_product_property
    defaults: { _controller: StoreBackendBundle:Product:editProperty }

update_product_property:
    path: /{id}/{propertyId}/add_product_property
    defaults: { _controller: StoreBackendBundle:Product:editProperty }

remove_product_property:
    path: /{id}/remove_product_property
    defaults: { _controller: StoreBackendBundle:Product:removePropertyValue }

edit_product_tag:
    path: /{id}/add_product_tag
    defaults: { _controller: StoreBackendBundle:Product:editTag }

#######
user_manage:
    path: /user
    defaults: { _controller: StoreBackendBundle:User:index }

user_profile:
    path: /{userId}/user
    defaults: { _controller: StoreBackendBundle:User:user }

####
shipment:
    path: /shipment
    defaults: { _controller: StoreBackendBundle:Shipment:index }

shipment_edit:
    path: /{id}/shipment_edit
    defaults: { _controller: StoreBackendBundle:Shipment:index }

shipment_remove:
    path: /{id}/shipment_remove
    defaults: { _controller: StoreBackendBundle:Shipment:removeShipment }

product_property:
    path: /product_property
    defaults: { _controller: StoreBackendBundle:ProductProperty:index }

payment_manage:
    path: /payment_manage
    defaults: { _controller: StoreBackendBundle:Payment:index }

payment_remove:
    path: /{id}/remove_payment
    defaults: { _controller: StoreBackendBundle:Payment:remove }

payment_set_default:
    path: /{id}/set_default_payment
    defaults: { _controller: StoreBackendBundle:Payment:setDefault }

order_manage:
    path: /order_manage
    defaults: { _controller: StoreBackendBundle:Order:index }

order_update:
    path: /{orderId}/order_update
    defaults: { _controller: StoreBackendBundle:Order:update }


mail:
    path: /mail
    defaults: { _controller: StoreBackendBundle:Message:index }

edit_mail:
    path: /{id}/edit_mail
    defaults: { _controller: StoreBackendBundle:Message:index }

remove_mail:
    path: /{id}/remove_mail
    defaults: { _controller: StoreBackendBundle:Message:remove }

prew_mail:
    path: /{id}/preview_mail
    defaults: { _controller: StoreBackendBundle:Message:preview }
