store:
    path: /
    defaults: { _controller: StoreBackendBundle:Home:home }

######
product_manage:
    path:     /product
    defaults: { _controller: StoreBackendBundle:Product:index }

product_trash_manage:
    path:     /product_trash
    defaults: { _controller: StoreBackendBundle:Product:trash }

product_edit:
    path: /{id}/product
    defaults: { _controller: StoreBackendBundle:Product:edit }

product_gallery:
    path: /{id}/gallery
    defaults: { _controller: StoreBackendBundle:Product:gallery }

product_gallery_action:
    path: /{id}/gallery/{action}
    defaults: { _controller: StoreBackendBundle:Product:editGallery }

product_remove:
    path: /{id}/product/remove
    defaults: { _controller: StoreBackendBundle:Product:remove }

product_resume:
    path: /{id}/product/resume
    defaults: { _controller: StoreBackendBundle:Product:resume }

product_category:
    path: /product/category
    defaults: { _controller: StoreBackendBundle:Category:index }

product_category_edit:
    path: /{id}/category/edit
    defaults: { _controller: StoreBackendBundle:Category:edit }

product_to_category:
    path: /{productId}/addTo/{categoryId}/{dropCategory}
    defaults: { _controller: StoreBackendBundle:Category:addProductToCategory }

#######
user_manage:
    path: /user
    defaults: { _controller: StoreBackendBundle:User:index }